### ISSUE TITLE
Index error in RollDieDynamic.py 

### ISSUE THREAD

**Issue by creepypuppet** [pdeitel/PythonForProgrammers#40]
![Screenshot_1](https://user-images.githubusercontent.com/68145076/179742943-1719d05a-1ae6-4869-a890-a561cfdc61c9.png)

**Comment by pdeitel** [comment]
Sorry, just saw this. Did you supply the command line arguments?

**Comment by pdeitel** [comment]
For example, the following runs 6000 animation frames with one die-roll in each:

ipython RollDieDynamic 6000 1
