### ISSUE TITLE
ch01 error messages

### ISSUE THREAD

**Issue by mbjohnsonmn** [pdeitel/PythonForProgrammers#41]
I'm coming with ~2 years experience with R, but new to python. Running the first example in the book produced two errors, The first was  "No module named 'seaborn`. I ran pip install seaborn which seemed to have solved that. Now I am stuck on this: **"TypeError: barplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given**." I gather it has something to do with a missing 'self' but I'm not sure how to fix it. Any suggestion? 
![ch01 example errors](https://user-images.githubusercontent.com/12174375/200596075-3a0b8b58-b6e1-464b-a14e-39dd0c6222f7.JPG)

**Comment by robb-romans** [comment]
Here is a fix.
https://github.com/pdeitel/PythonForProgrammers/blob/master/examples/ch01/RollDieDynamic.py#L17

Change line 17 to:  `axes = sns.barplot(x=faces, y=frequencies, palette='bright')  # new bars`

**Comment by mbjohnsonmn** [comment]
Okay, so not to miss the teachable moment, the library no longer allows implicit, positional assignment of the x and y arguments. True? Is that a common change in python libraries within the last four years?

**Comment by pdeitel** [comment]
Correct. You must explicitly use the x and y parameter names now to call the function as I did.

**Comment by robscurity** [comment]
instead of "faces" change to "values"
axes = sns.barplot(x=values, y=frequencies, palette='bright')

**Comment by oppiet30** [comment]
I get a different error.
[oppie@dell ch01]$ ls
RollDieDynamic.py
[oppie@dell ch01]$ python RollDieDynamic.py
Traceback (most recent call last):
  File "/home/oppie/PythonForProgrammers/examples/ch01/RollDieDynamic.py", line 30, in <module>
    number_of_frames = int(sys.argv[1])
                           ~~~~~~~~^^^
IndexError: list index out of range
[oppie@dell ch01]$ python --version
Python 3.12.3
[oppie@dell ch01]$

Do I need to do something?

The ^^^ is suppose to be under the argv.

**Comment by pdeitel** [comment]
Hi Robert,

What is the command you used to run the program? 

This program requires two "arguments": the first is the number of animation frames and the second is the number of die rolls to simulate per animation frame. So

`  ipython RollDieDynamic.py  600  1`

would run the the animation for 600 frames, simulating one die roll per frame.

Let me know if you have other questions.

Best,
Paul

**Comment by oppiet30** [comment]
Yeah, I should have read the chapter instead of blindly trying to run a program.
I guess there isn't a way to do this on a headless system. I am ssh'ed into the linux computer.
